Fixed Sanitization and escaping
weDevsOfficial/wp-project-manager pull request #427
Opened 2021-11-08 05:15 UTC by ManiruzzamanAkash

[fix] Fixed Sanitisation for Unsanitized echo and print

2021-11-09 15:56 UTC, tanmayjay requested changes

2021-11-09 15:56 UTC, tanmayjay commented on core/Cli/Commands.php
> +		    $wpdb->query( $wpdb->prepare( "TRUNCATE TABLE {$wpdb->prefix}%s", $table ) );
Kindly change the line as below for proper use of placeholder:
`$wpdb->query( $wpdb->prepare( "TRUNCATE TABLE %s", $wpdb->prefix . $table ) );`
And there is a extra tab at start of the line.

2021-11-09 15:56 UTC, tanmayjay commented on core/Promotions/Offers.php
> +        if ( ! isset( $_GET['page'] ) || 'pm_projects' !== $_GET['page'] ) { // phpcs:disable WordPress.Security.NonceVerification
Sanitize the variable before using.
`'pm_projects' !== sanitize_text_field( wp_unslash( $_GET['page'] ) )`

2021-11-09 15:56 UTC, tanmayjay commented on core/User_Profile/Profile_Update.php
> +                    <th><?php esc_html_e( 'Capability', 'pm-pro' ); ?> </th>
The domain here is supposed to be `wedevs-project-manager`

2021-11-09 15:56 UTC, tanmayjay commented on views/emails/html/new-comment.php
> +                                    Test Comment: <?php echo wp_kses_data( $content ); ?>
Escape the string here and make it translatable as well.
`<?php echo esc_html__( 'Test Comment: ', 'wedevs-project-manager' ) . wp_kses_data( $content ); ?>`

2021-11-09 15:56 UTC, tanmayjay commented on views/emails/html/new-message.php
> +                                            alt="<?php echo esc_html( $assign->display_name ); ?>" title="<?php echo esc_html( $assign->display_name ); ?>" width="33" height="33"
Use `esc_attr` as these values are being used as the values of attributes.
`alt="<?php echo esc_attr( $assign->display_name ); ?>" title="<?php echo esc_attr( $assign->display_name ); ?>" width="33" height="33"`

2021-11-09 15:56 UTC, tanmayjay commented on views/emails/html/new-task.php
> +    <title><?php echo esc_html_e( 'Your Message Subject or Title', 'wedevs-project-manager' ); ?></title>
`echo` is not needed while using `esc_html_e`

2021-11-09 15:56 UTC, tanmayjay commented on views/emails/html/update-project.php
> +                                                esc_html_e( 'has been updated by', 'wedevs-project-manager' ),
`_e` is not needed inside `printf`. use `__` instead.
However the sentece should be intact to make a proper and flexible translation.
```
        printf(
            esc_html__( 'The project "%1$s" has been updated by %2$s', 'wedevs-project-manager'  ),
            $title,
            $updater['data']['display_name']
        );
```

2021-11-09 15:56 UTC, tanmayjay commented on views/emails/html/update-task.php
> +                                Test Update task: <?php echo empty( $description['html'] ) ? esc_html_e( 'No description found!', 'wedevs-project-manager' ) : wp_kses_data( $description['html'] ); ?>
Is this for test purpose? Found a similar thing above. If not, change the line as below:
```
<?php echo esc_html__( 'Test Update task: ', 'wedevs-project-manager' ) . empty( $description['html'] ) ? esc_html__( 'No description found!', 'wedevs-project-manager' ) : wp_kses_data( $description['html'] ); ?>
```

2021-11-10 03:16 UTC, ManiruzzamanAkash commented on core/Promotions/Offers.php
> +        if ( ! isset( $_GET['page'] ) || 'pm_projects' !== $_GET['page'] ) { // phpcs:disable WordPress.Security.NonceVerification
Is that necessary in isset checking? I don't find any sanitization in if with isset block in WordPress core even.

2021-11-10 10:05 UTC, tanmayjay approved these changes

2021-11-10 10:08 UTC, merged